from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime

def generate_formal_briefing_pdf(content_markdown: str, user_name: str):
    """Generates a formal government-branded PDF briefing."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'HeaderTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor("#1e293b"),
        alignment=1,
        spaceAfter=12,
        fontName="Helvetica-Bold"
    )
    
    sub_header_style = ParagraphStyle(
        'SubHeader',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor("#64748b"),
        alignment=1,
        spaceAfter=30,
        fontName="Helvetica-BoldOblique",
        leading=10
    )

    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=colors.HexColor("#4f46e5"),
        spaceBefore=15,
        spaceAfter=10,
        fontName="Helvetica-Bold"
    )

    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor("#334155"),
        leading=14,
        fontName="Helvetica"
    )

    elements = []

    # 1. Letterhead / Department Info
    elements.append(Paragraph("GOVERNMENT OF TELUGU STATE", title_style))
    elements.append(Paragraph("MINISTRY OF INFORMATION & PUBLIC RELATIONS", sub_header_style))
    
    # Horizontal Line
    line_data = [[""]]
    line_table = Table(line_data, colWidths=[6.5*inch])
    line_table.setStyle(TableStyle([('LINEBELOW', (0,0), (-1,-1), 1, colors.black)]))
    elements.append(line_table)
    elements.append(Spacer(1, 20))

    # 2. Metadata (Date, Prepared By)
    meta_data = [
        [Paragraph(f"<b>DATE:</b> {datetime.now().strftime('%B %d, %Y')}", body_style), 
         Paragraph(f"<b>REPORT ID:</b> GDI-{datetime.now().strftime('%Y%m%d')}", body_style)],
        [Paragraph(f"<b>PREPARED BY:</b> {user_name}", body_style), 
         Paragraph("<b>CLASSIFICATION:</b> OFFICIAL / SENSITIVE", body_style)]
    ]
    meta_table = Table(meta_data, colWidths=[3.25*inch, 3.25*inch])
    meta_table.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'TOP')]))
    elements.append(meta_table)
    elements.append(Spacer(1, 30))

    # 3. Content Parsing (Simpler Markdown conversion for PDF)
    lines = content_markdown.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        if line.startswith('# '):
            elements.append(Paragraph(line.replace('# ', '').upper(), title_style))
        elif line.startswith('## '):
            elements.append(Paragraph(line.replace('## ', '').upper(), section_style))
        elif line.startswith('### '):
            elements.append(Paragraph(line.replace('### ', '').upper(), section_style))
        elif line.startswith('* ') or line.startswith('- '):
            clean_line = line[2:]
            elements.append(Paragraph(f"• {clean_line}", body_style))
            elements.append(Spacer(1, 4))
        else:
            # Handle bolding in body
            line = line.replace('**', '<b>').replace('**', '</b>')
            elements.append(Paragraph(line, body_style))
            elements.append(Spacer(1, 10))

    # 4. Watermark / Security Footer (ReportLab Draw Inline or Canvas)
    def add_watermark(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica-Bold', 60)
        canvas.setStrokeColor(colors.lightgrey)
        canvas.setFillColor(colors.lightgrey, alpha=0.1)
        canvas.translate(A4[0]/2, A4[1]/2)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, "GOVDIGEST OFFICIAL")
        canvas.restoreState()
        
        # Footer
        canvas.setFont('Helvetica', 8)
        canvas.drawString(inch, 0.75*inch, f"Generated by GovDigest Intelligence System | Page {doc.page}")
        canvas.drawRightString(A4[0]-inch, 0.75*inch, "CONFIDENTIAL")

    doc.build(elements, onFirstPage=add_watermark, onLaterPages=add_watermark)
    
    buffer.seek(0)
    return buffer
